---
# Configure remote machine to be a PostgreSQL server with development headers.
#
- apt:                  pkg={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2

- postgresql_db:        name={{ item }}
  sudo_user:            postgres
  with_items:           virtualhosts

- postgresql_user:      db={{ item.db }} name={{ item.name }} password={{ item.password }} priv=ALL role_attr_flags=SUPERUSER
  sudo_user:            postgres
  with_items:
    - { db: "www.strategiestrijd.nl", name: "{{ pg_production_user }}", password: "{{ pg_production_pass }}" }
    - { db: "staging.strategiestrijd.nl", name: "{{ pg_staging_user }}", password: "{{ pg_staging_pass }}" }