---
# Configure remote machine to be a PostgreSQL server with development headers.
#
- apt:                  pkg={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2

- postgresql_db:        name={{ item }}
  sudo_user:            postgres
  with_items:
    - production.{{ domain }}
    - staging.{{ domain }}

- postgresql_user:      db={{ item }} name=deploy priv=ALL role_attr_flags=SUPERUSER
  sudo_user:            postgres
  with_items:
    - production.{{ domain }}
    - staging.{{ domain }}
