# Ansible Playbook to manage Space Babies hosts
# Based on https://github.com/jlund/mazer-rackham
---
- hosts:        all
  remote_user:  joost
  sudo:         yes

  roles:
    - common

- hosts:        rails
  remote_user:  joost
  sudo:         yes

  roles:
    - rails

