---

- user:       name=deploy

- name:       Install Ruby dependencies
  apt:        pkg={{ item }} state=present
  with_items: ruby_dependencies

- name:       Download the Ruby source
  get_url:    url={{ ruby_download_location }}
              dest=/usr/local/src/{{ ruby_version }}.tar.bz2
              sha256sum={{ ruby_checksum }}

- name:       Generate the Ruby installation script on the server
  template:   src=ruby.j2
              dest=/usr/local/src/install-ruby.sh

- name:       Run the Ruby installation script
  command:    /usr/local/src/install-ruby.sh
              creates=/usr/local/src/{{ ruby_version }}/ruby

- copy:       src=gemrc dest=/etc/gemrc

- command:    "gem install bundler
              creates=/usr/local/bin/bundle"

- name:       Ensure the Phusion PGP key is installed
  apt_key:    id=AC40B2F7 state=present url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"

- name:               Ensure the passenger apt repository is added
  apt_repository:     state=present repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger precise main'

- name:       Install Rails dependencies
  apt:        pkg={{ item }} state=present
  with_items: rails_dependencies

#- name:       Ensure the nginx configuration file is set
#  template:   src=nginx.j2
#              dest=/etc/nginx/nginx.conf
#  notify:
#    - Restart nginx

- name:       Ensure nginx is running
  service:    name=nginx state=started enabled=yes

