---
# Defines tasks applicable across all machines in the infrastructure.

- apt:        upgrade=yes
              update_cache=yes
              cache_valid_time=3600

- name:       Configure SSH to only allow key-based auth
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^#?PasswordAuthentication"
              line="PasswordAuthentication no"
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^#?PubkeyAuthentication"
              line="PubkeyAuthentication yes"
  notify:
    - Restart SSH

- name:       Install essential packages for every server
  apt:        pkg={{ item }} state=present
  with_items: prerequisites

- name:         Check status of ufw
  command:      ufw status
  register:     ufw_status
  changed_when: False

- name:         Check config of ufw
  command:      cat /etc/ufw/ufw.conf
  register:     ufw_config
  changed_when: False

- command:      ufw default deny
- command:      ufw limit ssh
- command:      ufw allow http
- command:      ufw allow https

- name:       Enable ufw
  command:    ufw --force enable
  when:       "ufw_status.stdout.startswith('Status: inactive') or 'ENABLED=yes' not in ufw_config.stdout"
