- name:         ensure packages are up to date
  apt:          upgrade=yes update_cache=yes cache_valid_time=3600

- name:         Configure SSH to only allow key-based auth
  lineinfile:   dest=/etc/ssh/sshd_config
                regexp="^#?PasswordAuthentication"
                line="PasswordAuthentication no"
  lineinfile:   dest=/etc/ssh/sshd_config
                regexp="^#?PubkeyAuthentication"
                line="PubkeyAuthentication yes"
  notify:
    - Restart SSH

- name:         install essential packages for every server
  apt:          pkg={{ item }} state=present
  with_items:
    - ufw
    - git-core
    - unattended-upgrades

- ufw:          state=enabled policy=deny
- ufw:          rule=allow port=ssh
- ufw:          rule=allow port=http
- ufw:          rule=allow port=https

- name:         check current timezone
  shell:        cat /etc/timezone
  register:     current_zone

- name:         set timezone
  copy:         content={{ timezone }} dest=/etc/timezone owner=root group=root mode=0644 backup=yes
  when:         current_zone.stdout != timezone
  notify:
    - update timezone
